# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: gogs

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Download gogs
      working-directory: "C:/"
      shell: pwsh
      run: |
        Get-Volume
        git clone https://github.com/gogs/gogs.git C:/gogs-source --recursive
        cd C:/gogs-source
        
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...
    
    - name: Package output files
      working-directory: "D:/"
      shell: pwsh
      run: |
        tree C:/gogs-source
