# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: gogs

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Build gogs
      working-directory: "D:/"
      shell: pwsh
      run: |
        git clone --depth 1 https://github.com/gogs/gogs.git D:/gogs-source --recursive
        cd D:/gogs-source
        go build -ldflags "-s -w" -o gogs

    - name: Tree gogs
      working-directory: "D:/"
      shell: pwsh
      run: |
        gci -Recurse -Filter "*gogs*.exe" -File -ErrorAction SilentlyContinue -Path "D:\"

